import { useEffect, useMemo, useState } from 'react';
import { loadProviders } from '../api';
import type { ProviderRecord } from '../types';
import { dateTime, statusTone, wordsMatch } from '../ui';

export function SystemsPage() {
  const [providers, setProviders] = useState<ProviderRecord[]>([]);
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); loadProviders(controller.signal).then(result => { setProviders(result.providers || []); setError(''); }).catch(requestError => { if ((requestError as Error).name !== 'AbortError') setError((requestError as Error).message); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  const visible = useMemo(() => providers.filter(provider => wordsMatch(query, [provider.name, provider.group, provider.status, provider.owner, provider.endpoint])), [providers, query]);
  const selected = providers.find(row => row.id === selectedId) || null;
  return <main className={`operations-workspace resource-workspace ${selected ? 'has-detail' : ''}`}><section className="operations-index"><header className="workspace-title"><div><span>Connection center</span><h1>Systems</h1></div></header><div className="provider-summary"><span><strong>{providers.filter(row => /connected|live/i.test(row.status || '')).length}</strong> live</span><span><strong>{providers.filter(row => /ready|prepared|manual/i.test(row.status || '')).length}</strong> prepared</span><span><strong>{providers.filter(row => /needed|blocked|missing|error/i.test(row.status || '')).length}</strong> attention</span></div><label className="workspace-search"><span>/</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search Stripe, email, Star, storage, GPS" /></label>{error ? <div className="inline-alert error">{error}</div> : null}<div className="record-list">{loading ? <div className="empty-state">Loading provider status...</div> : null}{visible.map(provider => <button type="button" key={provider.id} className={provider.id === selectedId ? 'record-row active' : 'record-row'} onClick={() => setSelectedId(provider.id)} aria-label={`Open ${provider.name || provider.id} system details`}><span className={`status-line ${statusTone(provider.status)}`} /><span className="record-main"><strong>{provider.name || provider.id}</strong><span>{provider.group || 'Platform integration'}</span></span><span className="record-side"><b>{provider.status || 'Setup needed'}</b><time>{provider.lastTestAt ? dateTime(provider.lastTestAt) : 'Not live-tested'}</time></span></button>)}</div></section><section className="operations-detail">{!selected ? <div className="detail-empty"><strong>Select a system</strong><span>Provider status is evidence-based and never guessed.</span></div> : <div className="static-detail"><header className="detail-header"><button type="button" className="detail-back" onClick={() => setSelectedId('')}>Back</button><div><span>{selected.group || 'Integration'}</span><h2>{selected.name || selected.id}</h2></div><em className={`status-chip ${statusTone(selected.status)}`}>{selected.status || 'Setup needed'}</em></header><div className="detail-scroll"><dl className="detail-list"><div><dt>Owner</dt><dd>{selected.owner || 'Not assigned'}</dd></div><div><dt>Last live test</dt><dd>{selected.lastTestAt ? dateTime(selected.lastTestAt) : 'Not completed'}</dd></div><div><dt>Result</dt><dd>{selected.lastTestResult || 'No live test result saved'}</dd></div><div><dt>Endpoint</dt><dd>{selected.endpoint || 'Provider connection not configured'}</dd></div></dl><section className="detail-note"><span>Launch proof</span><p>{selected.liveTest || selected.notes || 'This provider needs a documented live test before the platform can rely on it.'}</p></section></div></div>}</section></main>;
}
