export type PortalRecord = {
  id?: string;
  name?: string;
  customer?: string;
  title?: string;
  type?: string;
  status?: string;
  stage?: string;
  tone?: string;
  body?: string;
  subject?: string;
  direction?: string;
  channel?: string;
  phone?: string;
  email?: string;
  username?: string;
  vehicle?: string;
  vehicleId?: string;
  vin?: string;
  plate?: string;
  stock?: string;
  licensePlate?: string;
  tracker?: string;
  mileage?: number | string;
  currentMileage?: number | string;
  amount?: number;
  balance?: number;
  weeklyAmount?: number;
  nextRun?: string;
  chargeTime?: string;
  frequency?: string;
  method?: string;
  provider?: string;
  paymentProvider?: string;
  cardLast4?: string;
  source?: string;
  notes?: string;
  issue?: string;
  due?: string;
  nextDue?: string;
  date?: string;
  createdAt?: string;
  updatedAt?: string;
  submittedAt?: string;
  paidAt?: string;
  expires?: string;
  portalUrl?: string;
  portalDownloadUrl?: string;
  url?: string;
  imageUrl?: string;
  weeklyPayment?: number;
  downPayment?: number;
  availability?: string;
  onlineVehicleId?: string;
  slug?: string;
};

export type CustomerPortal = {
  account: PortalRecord;
  summary: Record<string, unknown>;
  application: PortalRecord;
  applications: PortalRecord[];
  onboardingSessions: PortalRecord[];
  availableVehicles: PortalRecord[];
  customer: PortalRecord;
  contract: PortalRecord;
  recurring: PortalRecord;
  vehicle: PortalRecord;
  vehicles: PortalRecord[];
  payments: PortalRecord[];
  maintenance: PortalRecord[];
  claims: PortalRecord[];
  messages: PortalRecord[];
  documents: PortalRecord[];
  paymentRequests: PortalRecord[];
  cardSetupRequests: PortalRecord[];
  generatedAt: string;
};

export type CustomerPortalEnvelope = { ok: boolean; portal: CustomerPortal };
export type CustomerNotification = { id: string; title?: string; body?: string; tone?: string; at?: string; read?: boolean; url?: string };
export type CustomerNotifications = { ok: boolean; notifications: CustomerNotification[]; unreadCount: number };
